name: Test Self-Hosted Runner with Docker

on: [push, pull_request]

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print System Info
        run: uname -a

      - name: List Files
        run: ls -alh

      - name: Build Docker Image
        run: sudo docker build -t my-html-server docker-html/

      - name: Run Docker Container
        run: |
          sudo docker stop my-html-server || true
          sudo docker rm my-html-server || true
          sudo docker run -d --name my-html-server -p 8080:80 my-html-server
